spring:
  application:
    name: mangalfera
  datasource:
    url: jdbc:postgresql://168.231.102.95:5433/mangalfera
    username: postgres
    password: YOUR_VERY_STRONG_PASSWORD_HERE
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
